swagger: "2.0"
info:
  version: "1.0.0"
  title: "Deno oak starter API"
  contact:
    email: "asad.dk.bd@gmail.com"
host: "localhost:8000"
tags:
- name: "Auth"
  description: "JWT authentication"
- name: "User"
  description: "User enity CRUD operation"
schemes:
- "http"
paths:
  /login:
    post:
      tags:
      - "Auth"
      summary: "User login"
      operationId: "login"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/LoginRequest"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/LoginResponse"
        "400":
          description: "Invalid request"
        "401":
          description: "Unauthorized"
      security:
      - petstore_auth:
        - "write:pets"
        - "read:pets"
  /register:
    post:
      tags:
      - "Auth"
      summary: "Register end user"
      operationId: "register"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/RegistrationRequest"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/RegistrationResponse"
        "400":
          description: "Invalid request"
  
securityDefinitions:
  petstore_auth:
    type: "oauth2"
    authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:pets: "modify pets in your account"
      read:pets: "read your pets"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  LoginRequest:
    type: "object"
    properties:
      email:
        type: "string"
        format: "string"
      password:
        type: "string"
        format: "string"
  LoginResponse:
    type: "object"
    properties:
      access_token:
        type: "string"
        format: "string"
      refresh_token:
        type: "string"
        format: "string"
  RegistrationRequest:
    type: "object"
    properties:
      name:
        type: "string"
        format: "string"
      email:
        type: "string"
        format: "string"
      password:
        type: "string"
        format: "string"
  RegistrationResponse:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"
      name:
        type: "string"
        format: "string"
      email:
        type: "string"
        format: "string"
      roles:
        type: "string"
        format: "string"
      is_active:
        type: "boolean"
      created_at:
        type: "string"
        format: "date-time"
      updated_at:
        type: "string"
        format: "date-time"

      
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"